### ISSUE TITLE
白屏

### ISSUE THREAD

**Issue by gxh-apologize** [Wayaer/flutter_curiosity#2]
当有输入框的时候，弹起键盘后这个扫码页面就白屏了。返回这个页面在进入还是白屏。
有时候在扫码页面时间很久，导致锁屏后偶尔也会白屏。

出现了白屏，退出app在点进来也不行。需要杀死app再重启app才会正常。
请问这个是什么原因引起的？

**Comment by Wayaer** [comment]
是android端么？ 用的是新版Camera么？ androidOldCamera is true ?

**Comment by gxh-apologize** [comment]
@Wayaer 是android端       androidOldCamera is false

**Comment by Wayaer** [comment]
试试 androidOldCamera 设置为true

**Comment by gxh-apologize** [comment]
@Wayaer true的话，是黑屏，就是摄像头的预览画面是黑的了，但是好像还可以扫到

**Comment by Wayaer** [comment]
应该是PlatformView的问题，过几天会改成texture，再看一下

**Comment by gxh-apologize** [comment]
@Wayaer 好的，谢谢啦

**Comment by Wayaer** [comment]
可以考虑先使用 r_scan， 但是那个条形码得横屏才可以

**Comment by gxh-apologize** [comment]
@Wayaer 好的
